### ISSUE TITLE
Pull Regression: Label with full width on textarea

### ISSUE THREAD

**Issue by Escalion** [hperrin/svelte-material-ui#117]
When using max prop with PR #116, the input (expected) shrinks to match.
Adding the prop `fullwidth=true` allows to set the input as full width again.
However, with this prop set, the floating label function is disabled. This looks to be by design in Textfield.svelte

Removing L48, and `&& !fullwidth` on L60 and L53 resolves this issue but I don't want to submit a PR until there is clarification as to why it was decided to not support floating label on full width inputs?

Thanks, Esc

**Comment by Escalion** [comment]
Just going to add a further regression of fullwidth when coupled with outlined.
fullwidth + outlined results in some very strange rendering. Looking into it now

**Comment by defianceblack** [comment]
[@material/textfield#full-width](https://github.com/material-components/material-components-web/tree/master/packages/mdc-textfield#full-width):

> Note: Do not use mdc-text-field--outlined to style a full width text field.

> Note: Do not use mdc-floating-label within mdc-text-field--fullwidth. Labels should not be included as part of the DOM structure of a full width text field.

**Comment by hperrin** [comment]
Since there is a new release (5.0), and this issue was filed prior to that release and hasn't had any updates in at least six months, I'm going to close it as part of a mass issue clean up. If this issue is still relevant, please re-open it and mention me in a comment, and I will triage the issue into a relevant milestone. Thank you for your patience, and I apologize for any inconvenience.
