### ISSUE TITLE
Working with last committed version

### ISSUE THREAD

**Issue by barbagus** [hperrin/svelte-material-ui#122]
I cannot seem to be able to work with last committed version. At the time I am writing this, I am stuck with v1.0.0-beta.20 (with the Riplle.js console.log) of the packages when doing:

`npm install -D hperrin/svelte-material-ui`

I realize this is probably just me not knowing how to work properly with npm/git etc. If anyone can point me to the right direction however, thanks.

**Comment by collinsleewyatt** [comment]
If you're working with a project that already has Svelte Material UI installed, you'll need to update your package.json file to the version you want.

**Comment by hperrin** [comment]
Since there is a new release (5.0), and this issue was filed prior to that release and hasn't had any updates in at least six months, I'm going to close it as part of a mass issue clean up. If this issue is still relevant, please re-open it and mention me in a comment, and I will triage the issue into a relevant milestone. Thank you for your patience, and I apologize for any inconvenience.
