### ISSUE TITLE
Upgrading to "svelte-material-ui": "^1.0.0-beta.21" causes Uncaught ReferenceError: IconButton is not defined

### ISSUE THREAD

**Issue by thubalek** [hperrin/svelte-material-ui#131]
Hello, I updated `svelte-material-ui` to `1.0.0-beta.21` and I'm getting 

```
Uncaught ReferenceError: IconButton is not defined
    at main.js:5
```

since that upgrade. 

Any idea what may be wrong?

**Comment by hperrin** [comment]
Since there is a new release (5.0), and this issue was filed prior to that release and hasn't had any updates in at least six months, I'm going to close it as part of a mass issue clean up. If this issue is still relevant, please re-open it and mention me in a comment, and I will triage the issue into a relevant milestone. Thank you for your patience, and I apologize for any inconvenience.
