### ISSUE TITLE
Number are reformatted

### ISSUE THREAD

**Issue by 0cv** [hperrin/svelte-material-ui#135]
Like we can see at the bottom of this demo (https://sveltematerialui.com/demo/textfield), when typing a long number (7 or more Characters in Chrome), the number is automatically reformatted with exponential. It's most of the time not really user-friendly and at best confusing. The culprit seems to be this line:
https://github.com/hperrin/svelte-material-ui/blob/master/packages/textfield/Input.svelte#L59

A number, which is already a number shall come into the default scenario (`value = e.target.value`)

![image](https://user-images.githubusercontent.com/1253866/82652383-d0d7a700-9c1d-11ea-9d0d-05d71c5700fa.png)

**Comment by robations** [comment]
I think this might be causing another problem, which (coincidentally) I've just spotted.

Expected:
1. number input contains value "100"
2. move cursor to start of input
3. press delete key (to delete "1")
4. input field contains value "00"
5. type "2"
6. input field contains value "200"

Actual:
4. input field contains value "0" and cursor is at end of input
5. type "2"
6. input field contains value "2"

**Comment by hperrin** [comment]
Since there is a new release (5.0), and this issue was filed prior to that release and hasn't had any updates in at least six months, I'm going to close it as part of a mass issue clean up. If this issue is still relevant, please re-open it and mention me in a comment, and I will triage the issue into a relevant milestone. Thank you for your patience, and I apologize for any inconvenience.

**Comment by robations** [comment]
@hperrin The issue I mention above (editing input vs reformatting) is still an issue on the demo page:

https://sveltematerialui.com/demo/textfield
