### ISSUE TITLE
Bleeding text boundaries in shaped-outlined Text Field component with leading/trailing Icon

### ISSUE THREAD

**Issue by tonyketcham** [hperrin/svelte-material-ui#136]
_Confirmed on both Chrome and Safari on the demo site: https://sveltematerialui.com/demo/textfield_
### Screenshots of the issue:
<img width="270" alt="Screenshot 2020-05-23 06 44 53" src="https://user-images.githubusercontent.com/43280336/82729931-827be400-9cc1-11ea-8a1b-c8084eecb111.png">
<img width="270" alt="Screenshot 2020-05-23 06 45 16" src="https://user-images.githubusercontent.com/43280336/82729938-890a5b80-9cc1-11ea-854d-aed067ee7774.png">
<img width="270" alt="Screenshot 2020-05-23 06 51 15" src="https://user-images.githubusercontent.com/43280336/82729965-d38bd800-9cc1-11ea-9672-27e5d137560c.png">
<img width="270" alt="Screenshot 2020-05-23 06 54 05" src="https://user-images.githubusercontent.com/43280336/82730004-34b3ab80-9cc2-11ea-8c04-87fd95639343.png">

### Possible solution:

For `withLeadingIcon`:
- conditionally changing `padding-left` on the input element from 32px to 48px.
<img width="270" alt="Screenshot 2020-05-23 07 05 28" src="https://user-images.githubusercontent.com/43280336/82730241-ed2e1f00-9cc3-11ea-997e-93013785ae04.png">

For `withTrailingIcon`:
- conditionally changing `padding-right` on the input element with from 32px to 48px.
<img width="270" alt="Screenshot 2020-05-23 07 07 12" src="https://user-images.githubusercontent.com/43280336/82730270-0c2cb100-9cc4-11ea-8305-84f495a4d167.png">

**Comment by hperrin** [comment]
Since there is a new release (5.0), and this issue was filed prior to that release and hasn't had any updates in at least six months, I'm going to close it as part of a mass issue clean up. If this issue is still relevant, please re-open it and mention me in a comment, and I will triage the issue into a relevant milestone. Thank you for your patience, and I apologize for any inconvenience.
