### ISSUE TITLE
Form field on primary surface

### ISSUE THREAD

**Issue by std-odoo** [hperrin/svelte-material-ui#137]
Is it possible to add an attribute `color` on the form fields (Textfield, Select, etc) to be able to add them on different surface ?

**Comment by wallw-bits** [comment]
I was also attempting this today. I tried:
```
<Textfield class="mdc-theme--on-primary" withLeadingIcon label="Search">
  <Icon class="material-icons mdc-theme--on-primary">search</Icon>
</Textfield>
```
`Icon` properly uses the text color for `mdc-theme--on-primary` but the rest of the `Textfield` does not.

**Comment by hperrin** [comment]
Since there is a new release (5.0), and this issue was filed prior to that release and hasn't had any updates in at least six months, I'm going to close it as part of a mass issue clean up. If this issue is still relevant, please re-open it and mention me in a comment, and I will triage the issue into a relevant milestone. Thank you for your patience, and I apologize for any inconvenience.
