### ISSUE TITLE
Struggling with PopUp Menu positioning and/or Menu being clipped by other elements

### ISSUE THREAD

**Issue by KevinAst** [hperrin/svelte-material-ui#145]
I am struggling to get one of my @smui PopUp Menus to fully display and position correctly.

[Here is a REPL](https://svelte.dev/repl/ab95d24ba2af45d683058594c4a68406?version=3.23.2) that demonstrates my problem.

The PopUp Menu is being activated from an `<Item>` element.

I am attempting to use a **manual anchor** for the Menu position.

1. If the `<Menu>` is instantiated outside the `<Item>` _(**uncheck** `Place Menu In Item`)_, it is fully visible, but is **NOT** anchored correctly.

2. If the `<Menu>` is instantiated inside the `<Item>` _(**check** `Place Menu In Item`)_, it seems as though it is being positioned, **however** it is being clipped by the boundaries of the `<Item>`. Also, I think this is using an automatic anchor (not really sure).

I must be doing something fundamentally wrong ... _it shouldn't be this hard_ :-(

Your help is greatly appreciated!

`</Kevin>`

**Comment by hperrin** [comment]
Since there is a new release (5.0), and this issue was filed prior to that release and hasn't had any updates in at least six months, I'm going to close it as part of a mass issue clean up. If this issue is still relevant, please re-open it and mention me in a comment, and I will triage the issue into a relevant milestone. Thank you for your patience, and I apologize for any inconvenience.
