### ISSUE TITLE
on:blur not triggering on Select

### ISSUE THREAD

**Issue by Zahara-Nour** [hperrin/svelte-material-ui#167]
I try to catch blur event in Select component, but it seems that it's not triggering.

```
 <Select            
        bind:value
        label="{label}"
        on:blur="{() => console.log('*** change ***')}"
 >
      {#each values as v}
      <Option value="{v.name}" selected="{value === v.name}">
      {v.name}
      </Option>
       {/each}
</Select>
```
I get nothing in console when I manually select another value.

**Comment by Zahara-Nour** [comment]
`on:change` works but if I set enhanced, none of the two events is triggering.

**Comment by JJK96** [comment]
Looking at in the source, it seems `on:blur` is not forwarded to the select/input

**Comment by hperrin** [comment]
Since there is a new release (5.0), and this issue was filed prior to that release and hasn't had any updates in at least six months, I'm going to close it as part of a mass issue clean up. If this issue is still relevant, please re-open it and mention me in a comment, and I will triage the issue into a relevant milestone. Thank you for your patience, and I apologize for any inconvenience.
