### ISSUE TITLE
Cannot get install for sapper to work

### ISSUE THREAD

**Issue by justageek** [hperrin/svelte-material-ui#172]
I worked through the sapper installation instructions using rollup and I get the following when trying to start the app

✗ server
Unexpected character '@' (Note that you need plugins to import files that are not JavaScript)
1: @import "smui-theme";
   ^
2: @import "./style";
✗ client
File to import not found or unreadable: smui-theme.
internal/modules/cjs/loader.js:895
  throw err;
  ^

Error: Cannot find module '/Users/briansmith/data/sapper-app/__sapper__/dev/server/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:892:15)
    at Function.Module._load (internal/modules/cjs/loader.js:742:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
> Server crashed

**Comment by csaltos** [comment]
I got the same error until I discover that postcss needs `extract` to `false` to work correctly with Sapper Svelte.

Please find here a complete template with Svelte Material UI working with Sapper -> https://github.com/csaltos/sapper-svelte-material-ui

For using it you may run these commands:

```bash
npx degit csaltos/sapper-svelte-material-ui app2
cd app2
npm i
npm run dev
```

and then open your browser at http://localhost:3000/

For details on what to change on an on going Sapper project please visit the commit https://github.com/csaltos/sapper-svelte-material-ui/commit/16790964c105f4b3fdf4840e7f5d3a86bf53633d (it's basically the same as the original instructions with the extract in false instead of true)

**Comment by csaltos** [comment]
Please also find the proposed fix at the README instructions in this PR -> https://github.com/hperrin/svelte-material-ui/pull/173

**Comment by csaltos** [comment]
and here a post with more info about it -> https://dev.to/csaltos/sapper-with-material-ui-35id

**Comment by MTyson** [comment]
Note to others: **read the instructions carefully when modifying rollup config**.

**Comment by hperrin** [comment]
Check out the new instructions for Sapper in the readme. I found a better approach that eliminates the flash of unstyled content.
