### ISSUE TITLE
View component and View demo buttons disappear

### ISSUE THREAD

**Issue by jd0e** [hperrin/svelte-material-ui#176]
Hi,

to reproduce:
1. Go to (click) https://sveltematerialui.com/demo/data-table/
- notice no View component or View demo buttons in top right corner
2. Click "Data Table" from menu on the left
- observe View component and View demo buttons magically appear.

Regards,

**Comment by hperrin** [comment]
Since there is a new release (5.0), and this issue was filed prior to that release and hasn't had any updates in at least six months, I'm going to close it as part of a mass issue clean up. If this issue is still relevant, please re-open it and mention me in a comment, and I will triage the issue into a relevant milestone. Thank you for your patience, and I apologize for any inconvenience.
