### ISSUE TITLE
Kitchen close

### ISSUE THREAD

**Issue by ISDEdtech** [hperrin/svelte-material-ui#182]
It it something to think about or am I doing it wrong?
I have found need for a kitchen.close() method, to close snackbar events.

export function close() {(config !== null) {component.close()}}

I think it would be a good addition.

**Comment by hperrin** [comment]
Since there is a new release (5.0), and this issue was filed prior to that release and hasn't had any updates in at least six months, I'm going to close it as part of a mass issue clean up. If this issue is still relevant, please re-open it and mention me in a comment, and I will triage the issue into a relevant milestone. Thank you for your patience, and I apologize for any inconvenience.
