### ISSUE TITLE
How to integrate with snowpack

### ISSUE THREAD

**Issue by simonh1000** [hperrin/svelte-material-ui#196]
Snowpack handles imports differently and I'm struggling to get the `@import "@material/theme/color-palette";` link to work

> Package "@material/theme/color-palette" not found. Have you installed it?

Anyone found a configuration that works?

**Comment by ztyankov** [comment]
I have the same issue. Snowpack and Svelte + TS worked like a charm. As soon as I added Material, things went down the drain. I'll be happy to hear if anyone got this working.

I tried some of the tutorials about Snowpack + Svelte + TailwindCSS, but I couldn't get their configs to work for Material.

**Comment by hperrin** [comment]
This looks similar to tabs, so if you can coerce tabs into doing what you want, I think that should work. I don't have plans to implement these myself, but if MDC-Web implements them, I will support them.

**Comment by hperrin** [comment]
Since there is a new release (5.0), and this issue was filed prior to that release and hasn't had any updates in at least six months, I'm going to close it as part of a mass issue clean up. If this issue is still relevant, please re-open it and mention me in a comment, and I will triage the issue into a relevant milestone. Thank you for your patience, and I apologize for any inconvenience.
