### ISSUE TITLE
First element of List does not ripple

### ISSUE THREAD

**Issue by tuckergordon** [hperrin/svelte-material-ui#198]
I noticed that the first item of a List does not ripple on click as the others do. This is visible in the [official demo](https://sveltematerialui.com/demo/list) on the "Simple List". 

I'm guessing this is an issue with SMUI and not with MDC, since the [example](https://material.io/components/lists) on Material.io does not have this issue.

**Comment by seaburrows** [comment]
The issue is caused by updating the first items `tabIndex` after mounting. 
This re-renders the list `Item` but the classes added by `Ripple` are not preserved and so the click effect does not appear.

Svelte is new to me so I'm not clear if there is an established way of handling this, but we can copy the classes at the same time to preserve:
```js
//// file: list/Item.svelte

    if (noneSelected) {
      // This is the first element, and no other element is selected, so the
      // tabindex should be '0'.
      tabindex = '0';

      if (ripple) {
        // Preserve the classes added by Ripple on re-render
        className = element.className;
      }
    }
```

Happy to raise a PR is this is the correct approach :+1:

**Comment by hperrin** [comment]
This is working now.
