### ISSUE TITLE
select opens inside dialog instead of on top

### ISSUE THREAD

**Issue by MTyson** [hperrin/svelte-material-ui#203]
![dialog-select](https://user-images.githubusercontent.com/54382/107672039-b3d28080-6c51-11eb-8191-16da501b77cb.png)

**Comment by kasokz** [comment]
Hello, I encountered this problem as well recently. Since the "enhanced" select doesn't actually use the native selection menu, it is affected by overflow behaviour. You need to change all parents including the dialog itself to allow overflow to be visible instead of scrolling. You can do so using the `overflow: visible` property.

**Comment by hperrin** [comment]
Since there is a new release (5.0), and this issue was filed prior to that release and hasn't had any updates in at least six months, I'm going to close it as part of a mass issue clean up. If this issue is still relevant, please re-open it and mention me in a comment, and I will triage the issue into a relevant milestone. Thank you for your patience, and I apologize for any inconvenience.

**Comment by hperrin** [comment]
This seems to be an issue with the MDC-Web library itself.

**Comment by hperrin** [comment]
If you don't mind, could you file this issue in their repo?
https://github.com/material-components/material-components-web/issues

**Comment by ergofobe** [comment]
Looks like this was already fixed upstream. See material-components/material-components-web#5590
