### ISSUE TITLE
How can I make this works with sveltekit ?

### ISSUE THREAD

**Issue by schmurfy** [hperrin/svelte-material-ui#214]
I tried : 
- installed the all in one package
- added `_smui-theme.scss` file
- I then got a bunch of errors saying `@material/xx` could not be found so I installed the missing packages and when I thought I was all set I now get a vite error saying it cannot the same `@material/xxx` packages...

setting up a new javascript frontend dev project is always so depressing and damn frustrating, why does it have to be so damn complicated...

**Comment by hperrin** [comment]
I haven't tried SvelteKit yet, but I've started working on updating to the latest upstream version of the MDC library, which might improve things.

**Comment by hperrin** [comment]
SMUI v3 will use MDC v10.

**Comment by arseneyr** [comment]
I believe the `@material/*` errors are caused by Vite attempting to resolve source map sources that don't exist. Specifically, the Material Component package has source maps that reference the original Typescript sources but do not include them in the package. I've opened https://github.com/vitejs/vite/issues/2892 so that Vite doesn't treat missing sources as a fatal error. 

As a workaround, I have a branch [here](https://github.com/arseneyr/vite/tree/smui-fix/packages/vite) that ignores missing source map errors. To install in your existing SvelteKit project:

```
npm install -D 'https://gitpkg.now.sh/arseneyr/vite/packages/vite?smui-fix'
```
or
```
yarn add -D 'https://gitpkg.now.sh/arseneyr/vite/packages/vite?smui-fix'
```

**Comment by unlocomqx** [comment]
The """solution""" is to delete the sourcemaps
```bash
cd node_modules/@material
find . -name "*.js.map" -type f -delete
```

Hopefully, this will get fixed https://github.com/vitejs/vite/issues/2892

**Comment by hperrin** [comment]
New SvelteKit example repo:
https://github.com/hperrin/smui-example-sveltekit

**Comment by hperrin** [comment]
And new instructions:
https://github.com/hperrin/svelte-material-ui/blob/master/INSTALL.md#sveltekit
