### ISSUE TITLE
Comparison/collaboration with Svelte Materialify

### ISSUE THREAD

**Issue by Immortalin** [hperrin/svelte-material-ui#217]
I found another Svelte Material library.

https://github.com/TheComputerM/svelte-materialify

What are the main differences between svelte-material-ui and svelte-materialify? Any room for collaboration?

**Comment by hperrin** [comment]
Well for one thing the comparison table on the homepage for Svelte Materialify is suspiciously inaccurate.

![image](https://user-images.githubusercontent.com/195918/114932784-bcc80580-9dec-11eb-806c-4d1cf2d5601d.png)

Svelte Material UI should have a check in every row except "Business and Enterprise support".

Also the "Customisable Components" count is pretty misleading. Counting things like "Dividers" and "Subheaders" as their own components isn't really helpful. SMUI has those too, but they aren't standalone packages, since you would never use them by themselves. Even then, SMUI has 36 unique packages, and every one of them has customizable components, usually several.

I'm pretty sure everything I've listed in the [features section](https://github.com/hperrin/svelte-material-ui#features) of the readme are also things that SMUI supports and Svelte Materialify doesn't.

**Comment by Florian-Schoenherr** [comment]
@hperrin to our defence: the chart is a bit old, some of it wasn't really there before, right? (I haven't made it).
@TheComputerM is working on a rewrite of the lib, he'll hopefully change that.
I mainly advocate for a way to benchmark components for easier comparison.
Some of SMUIs features seem to me like they break boundaries and might affect performance (but the approach _is_ interesting).

Keep up the good work!

**Comment by hperrin** [comment]
@Florian-Schoenherr, no, SMUI v1 and v2 also had all those checks.

**Comment by hperrin** [comment]
Hey @TheComputerM, thank you for posting the apology regarding the comparison table. I really appreciate it. :) Best of luck on your exams and your project rewrite.
