### ISSUE TITLE
Add comment for sveltejs/template users how to amend rollup configuration

### ISSUE THREAD

**Issue by korompaiistvan** [hperrin/svelte-material-ui#222]
** Is this for an existing documentation file? **
https://github.com/hperrin/svelte-material-ui/blob/master/INSTALL.md 

** What needs improvement? **
The rollup installation section mentions the additional lines that need to be added into rollup.config.js. That said most people (I imagine) would start with the sveltejs/template, so they would have the following line in their rollup config:
`css({ output: 'bundle.css' })`
https://github.com/sveltejs/template/blob/master/rollup.config.js#L48

This needs to be commented out, otherwise styling written into the component breaks.

**Comment by YJDoc2** [comment]
Hello, can you give some more details on this? 
I had created a template using sveltejs/template, and as you said, it does not seem to work with svelte-material ui. For example, when I use Layout Grid, all elements are being displayed in simple rows, one after other, instead of getting the grid layout. I tried to comment the css(...) in rollup config, but it does not make any difference, and the issue is still there. I checked with other components such as FAB as well to make sure that it wasn't an error in Layout-Grid itself.

Can you maybe post the complete working rollup config or give a bit more detailed instruction on what changes might be needed to make svelte-materia-ui work with the sveltejs/template?

Thank you.

**Comment by robsch** [comment]
Yes, same here. How to integrate this library?

**Comment by hperrin** [comment]
Please migrate to the new easy theming method. You won't need to modify your rollup config.
