### ISSUE TITLE
Select component height cannot be resized

### ISSUE THREAD

**Issue by masyukun** [hperrin/svelte-material-ui#223]
I need it to fit in my 35px height form, and Select is the ugly duckling. Textfield works like a charm with style="height: 35px;"

**Comment by hperrin** [comment]
Since there is a new release (5.0), and this issue was filed prior to that release and hasn't had any updates in at least six months, I'm going to close it as part of a mass issue clean up. If this issue is still relevant, please re-open it and mention me in a comment, and I will triage the issue into a relevant milestone. Thank you for your patience, and I apologize for any inconvenience.
