### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by pavolfranekdev** [hperrin/svelte-material-ui#354]
is this project dead? 
There are many open bugs. Should we migrate to another library?
Why aren't demos available? https://github.com/hperrin/svelte-material-ui/blob/master/site/src/routes/demo/button/_Simple.svelte

**Comment by Audhut** [comment]
seems like that what are the alternative options?

**Comment by pavolfranekdev** [comment]
https://madewithsvelte.com/ui-library

**Comment by hperrin** [comment]
Why would you think it's dead?

**Comment by hperrin** [comment]
There are many open issues, but most of them are invalid, because they relate to old versions. I'll close them when I get around to it. This is a project run by one person (me), so if you're used to getting tons of free support from other, bigger projects, you might feel a little on your own here, but that's the nature of open source. The code works and I am currently using it to build my own apps, so if you have any issues, feel free to ask in the Discord and someone can help you out.

**Comment by hperrin** [comment]
Also, there's literally a link to demos in the README file.

https://sveltematerialui.com

**Comment by hperrin** [comment]
A good thing to do if you're wondering if a project is dead would be to check whether it has had any recent commits or releases. The latest commit and release of this project was 3 days ago. You could use that as a pretty strong indicator that the project is not dead.
