### ISSUE TITLE
Any pre-made layouts

### ISSUE THREAD

**Issue by quantuminformation** [hperrin/svelte-material-ui#39]
One of the reasons I use vuetify is its amazing [themes](https://vuetifyjs.com/en/getting-started/pre-made-layouts).

I'm shopping around between this lib and the other svelte ones.

**Comment by hperrin** [comment]
Since there is a new release (5.0), and this issue was filed prior to that release and hasn't had any updates in at least six months, I'm going to close it as part of a mass issue clean up. If this issue is still relevant, please re-open it and mention me in a comment, and I will triage the issue into a relevant milestone. Thank you for your patience, and I apologize for any inconvenience.
