### ISSUE TITLE
Error thrown when number field is undefined

### ISSUE THREAD

**Issue by mwamp** [hperrin/svelte-material-ui#40]
Take a Textfield of type number
Erase content
notice : 
`TypeError: value is undefined; foundation.js:280`

This is thrown from the underlying mdc component which tries to count the string length of 'value'

Solutions : 
1 - do not update val when undefined
2 - update val by a default value when undefined
3 - A better solution?

Relevant code
In Input.svelte
 ```
  function toNumber(value) {
    return value === '' ? undefined : +value;
  }
  function valueUpdater(e) {
    switch (type) {
      case 'number':
      case 'range':
        value = toNumber(e.target.value);
        break;
      case 'file':
        files = e.target.files;
        // Fall through.
      default:
        value = e.target.value;
        break;
    }
  }
```

Suggested change (solution 2-)
 ```
  function toNumber(value) {
    return  +value;
  }
  function valueUpdater(e) {
    switch (type) {
      case 'number':
      case 'range':
        if( value!==='' ) value = toNumber(e.target.value);
        break;
      case 'file':
        files = e.target.files;
        // Fall through.
      default:
        value = e.target.value;
        break;
    }
  }
```
​

**Comment by eddiew** [comment]
I'm running into this as well. Looking through the material-components-web code, it looks like it only calls `.length` when counting the character-length of the input.

Rather than taking one of the approaches proposed here I think it makes more sense to change
`this.getValue().length`
to something like
`this.getValue() ? this.getValue().length : 0`
upstream.

I'll look into making a PR for this

**Comment by eddiew** [comment]
Submitted a PR that does the value/rawValue thing

**Comment by mwamp** [comment]
Wouldn't it be simpler in that case to just have : 
```
let valueProp = {};
  $: if (type === 'file') {
    delete valueProp.value;
  } else {
    valueProp.value = (value===undefined) ? '' : value;
  }
```
While we're at it I would replace `undefined` with `null`
Since this should only occur for number fields maybe having `NaN` would be even more semantic?
Or if we wish to define : `let invalid_number = Symbol()` and use this instead

**Comment by eddiew** [comment]
Oh duh good point. Thanks. I've updated the PR.
To your other point, I actually think `undefined` is the right value for an empty textfield, since the emptiness can be thought of simply as the absence of the value. `NaN` would make more sense for non-undefined inputs that fail to parse. And anyway, it's probably better to keep that part of the code as it is here to keep the PR self-contained.

**Comment by hperrin** [comment]
I liked the idea of having NaN represent a user inputting nothing, but NaN also doesn't have a length. My solution is to create a `new Number(Number.NaN)` and give it a length of 0. It works, but it is an unfortunate hacky solution. I guess this won't be solved properly without MDC upstream solving it first.

Fix: https://github.com/hperrin/svelte-material-ui/commit/95a2401a62970aeb5a720151187edcc3aca99a6e
