### ISSUE TITLE
How to use configured smui colors variables in svelte files ? 

### ISSUE THREAD

**Issue by yadomi** [hperrin/svelte-material-ui#444]
It might be a simple thing but I can't figure how to re-use theme variables once configured.

Let's say I have overrided the theme variables like so in `_smui-theme.scss` and compiled the theme: 

```scss
@use '@material/theme/index' as theme with (
  $primary: red,
  $secondary: blue,
);
```

and in my `App.svelte`:

```svelte

<div class="text">Some text</div>

<style type="text/scss">
  @use '@material/theme/index'

  .test {
    color: theme.$primary;
  }
</style>
```

When doing so, `theme.$primary` isn't red but has the default material color. The configuration is ignored.

What's the intended usage for this ?

**Comment by hperrin** [comment]
You should assign them to another variable that is forwarded, then use that variable in the use statement. That's what I understand is the common practice with Sass. You may also need to assign them in a different file, like "_vars.scss", and import that file to get the variables, since use statements need to be first.
