### ISSUE TITLE
Clarification in docs

### ISSUE THREAD

**Issue by ispyinternet** [hperrin/svelte-material-ui#56]
You state:
> You _should_ install the packages individually. Alternatively, you can install all of them at once with the svelte-material-ui package.

Given that it would be much easier to just install everything once, and assuming tree-shaking would ensure a minimal bundle, can you clarify why you make this _should_ statement?

Thanks!

**Comment by robations** [comment]
So a quick answer to this would be that `svelte-material-ui` doesn't re-export anything.

A longer answer might question whether `svelte-material-ui` should re-export the components (or somehow include them directly at build time, or be removed completely), because according to a strict usage of node modules it's currently useless. More so if you were to move to using plug and play package management.

For example, it's not safe to use `@smui/button` unless I explicitly reference it in `package.json` (because it might get removed or change to a breaking version unexpectedly).

**Comment by hperrin** [comment]
There is now a good reason to only install the packages you need. The theme builder builds the Sass for any package that is installed, regardless of whether you use it.
