### ISSUE TITLE
TypeError: m.getPropStore is not a function on <AutoAdjust {topAppBar}>

### ISSUE THREAD

**Issue by f0o** [hperrin/svelte-material-ui#573]
**Describe the bug**

**To Reproduce**
1. Go to https://github.com/hperrin/svelte-material-ui/blob/master/packages/site/src/routes/demo/top-app-bar/iframe/fixed/+page.svelte
2. Use that in your sveltekit ^1.0.0 application
3. Build
4. See error in browser console and a blank page

**Expected behavior**
Example should not error and actually work on latest sveltekit (since sveltekit is now being forced by svelte it seems)

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by f0o** [comment]
Turns out it was ts issue... Closing

**Comment by quasarchimaere** [comment]
i am not sure if this is a ts issue, i run into the same problem and it is causing the variant class to be missing in the produced `main` tag created by `AutoAdjust` ->  class="mdc-top-app-bar--short-fixed-adjust" is missing (for variant=short) and thus the navbar is placed above content hiding whats underneath


The workaround for now is that i add the  `mdc-top-app-bar--short-fixed-adjust` class to the AutoAdjust component in my layout directly, which is ok because my variant does not change dynamically, but its still a hack
