### ISSUE TITLE
Textfield (fullwidth) & label

### ISSUE THREAD

**Issue by ispyinternet** [hperrin/svelte-material-ui#58]
Should the label transition up into small font on fullwidth Textfields? Also notice the helper text gets a forced left margin (you can see these observations on your demo site)

Also think there is an issue using Icon with fullwidth.

**Comment by hperrin** [comment]
Since there is a new release (5.0), and this issue was filed prior to that release and hasn't had any updates in at least six months, I'm going to close it as part of a mass issue clean up. If this issue is still relevant, please re-open it and mention me in a comment, and I will triage the issue into a relevant milestone. Thank you for your patience, and I apologize for any inconvenience.
