### ISSUE TITLE
Can't filter a table through an Autocomplete field

### ISSUE THREAD

**Issue by melijimenez11** [hperrin/svelte-material-ui#626]
**Describe the bug**
I'm trying to filter a table using an Autocomplete field. When the user selects a value in Autocomplete, the filtering function isn't working correctly. 

**To Reproduce**
1. Go to ['...'](https://svelte.dev/repl/16c86a5b414a4f80ac282fba71bf1b6d?version=4.2.1) to look at the issue more closely
2. Select an option from the autocomplete field

**Expected behavior**
The table should display the rows that contain the selected value

**Screenshots**

**Comment by hperrin** [comment]
There are a couple issues with your code.

Your filter function is not actually returning a value, so it will always filter everything out.

You are both filtering from and assigning the result to `filteredProjects`, which means that once you filter something, it will be filtered out forever. Instead, you should have a const called `projects` that you filter and assign to `filteredProjects`.

The `SMUIAutocomplete:selected` event fires _before_ the value is updated, so that it can be cancelled. Instead of listening for the event, you should use a reactive variable.

Here is a version with these issues fixed:
https://svelte.dev/repl/5a0e70aca6df44a085bfd3d05f943b53?version=4.2.1
