### ISSUE TITLE
Slider steps in float

### ISSUE THREAD

**Issue by Amerlander** [hperrin/svelte-material-ui#69]
The slider is only able to change the value in integer steps.
The material components are originally able to step in floats, like 0.5.

This doesnt work:
`<Slider bind:value={5} min={1} max={7} step={0.5}  discrete displayMarkers />`

(edited, because the code wasn't visible)

**Comment by MintyMods** [comment]
Tested and it seems OK to me. Here is a [Repl ](https://svelte.dev/repl/f379dceff16f46ef9615003e665a5403?version=3.16.0) showing it stepping in increments of `.25`

**Comment by Amerlander** [comment]
Thank you for the reply.

I just compared with my setup and it seems that the discrete flag is breaking it:

<Slider bind:value min={0} max={10} step={.25} discrete />

**Comment by MintyMods** [comment]
The following [Repl ](https://svelte.dev/repl/889cb0d89e55418a8608830080db4a21?version=3) shows a couple of Slider examples  using discrete  step values of `.25`

- 0.25 - Not Working
- 1.25 - Working

I think this is due to a currently [open bug](https://github.com/material-components/material-components-web/issues/1426) within the material component.

**Comment by Amerlander** [comment]
okay I see, thank you for clearifying :)
