### ISSUE TITLE
Number input does not handle minus sign well

### ISSUE THREAD

**Issue by mwamp** [hperrin/svelte-material-ui#70]
Select field content or position cursor anywhere except the front and hit minus
   -> field gets erased

What to do to get a minus sign in 
  -> write digits and then reposition cursor in front to add the minus

Basic fix : 
```js
function valueUpdater(e) {
    switch (type) {
      case 'number':
      case 'range':
        if(e.data==="-"){ value="-0"; break;} //! This line added
        value = toNumber(e.target.value);
        break;
      case 'file':
        files = e.target.files;
        // Fall through.
      default:
        value = e.target.value;
        break;
    }
  }
```

Result behavior : any - inserted anywhere but in front will clear input and add '-0' to it
That would be fine by me

**Comment by hperrin** [comment]
Since there is a new release (5.0), and this issue was filed prior to that release and hasn't had any updates in at least six months, I'm going to close it as part of a mass issue clean up. If this issue is still relevant, please re-open it and mention me in a comment, and I will triage the issue into a relevant milestone. Thank you for your patience, and I apologize for any inconvenience.

**Comment by Kubitini** [comment]
This is still an issue. This behavior makes the number input unusable for me.
