### ISSUE TITLE
Validation multiple inputs

### ISSUE THREAD

**Issue by d0whc3r** [hperrin/svelte-material-ui#88]
I tested validation for "input$required" in TextField and it works well, but when I have 2 TextFields and both are "invalid" when i write some text in one of them it removes the "invalid" from all TextFields not only from which I write some text

**Comment by hperrin** [comment]
Since there is a new release (5.0), and this issue was filed prior to that release and hasn't had any updates in at least six months, I'm going to close it as part of a mass issue clean up. If this issue is still relevant, please re-open it and mention me in a comment, and I will triage the issue into a relevant milestone. Thank you for your patience, and I apologize for any inconvenience.
