### ISSUE TITLE
Validation TextField

### ISSUE THREAD

**Issue by d0whc3r** [hperrin/svelte-material-ui#89]
I have a TextField with "input$required" and when I click in input and then click outside it shows the invalid, this is ok, then I click again and write something, and without click outside it removes the "invalid", this is also ok, then I remove all the text but it only shows invalid when I click outside and this it is not ok I think

**Comment by hperrin** [comment]
Since there is a new release (5.0), and this issue was filed prior to that release and hasn't had any updates in at least six months, I'm going to close it as part of a mass issue clean up. If this issue is still relevant, please re-open it and mention me in a comment, and I will triage the issue into a relevant milestone. Thank you for your patience, and I apologize for any inconvenience.
